export default [
    "center.main.pushMsg",
    "center.main.kickUser",
    "info.main.getAssetInfo",
    "info.main.getRoleInfo",
    "info.main.getInviteRewardInfo",
    "info.main.getScoreInfo",
    "match.main.getRoomInfo",
    "match.main.match",
    "match.main.matchOk",
    "game.main.enterRoom",
    "game.main.frameMsg",
    "center.main.getRankData",
    "center.main.getInviteReward",
]